# language: minimal
language: minimal

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed batoleios/udagram-api-feed:v3
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user batoleios/udagram-api-user:v3
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend batoleios/udagram-frontend:v6
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy batoleios/udagram-reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push batoleios/udagram-api-feed:v3
  - docker push batoleios/udagram-api-user:v3
  - docker push batoleios/udagram-frontend:v6
  - docker push batoleios/udagram-reverseproxy:v3
